## ref: https://hub.docker.com/r/library/nextcloud/tags/
# image:
#   registry: docker.io
#   repository: library/nextcloud
#   flavor: apache
#   tag: 31.0.0-apache

# CRITICAL: Since HAProxy handles SSL, K3s sees HTTP traffic.
# This forces Nextcloud to treat connections as HTTPS to avoid broken CSS/JS.
phpClientHttpsFix:
  enabled: true
  protocol: https

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 20G
  tls: []
  hosts:
    - host: nextcloud.casarp.us
      paths:
        - path: /
          pathType: Prefix

# --- ROOT LEVEL CONFIGURATIONS ---

# 1. Persistence (Must be at the root, NOT indented under 'nextcloud')
persistence:
  enabled: true
  storageClass: longhorn
  accessMode: ReadWriteOnce
  size: 20Gi

# 2. Database Configuration (Internal SQLite)
internalDatabase:
  enabled: true
  name: nextcloud

# 3. Disable External Databases
externalDatabase:
  enabled: false

mariadb:
  enabled: false

postgresql:
  enabled: false

redis:
  enabled: false

# --- NEXTCLOUD APPLICATION CONFIG ---
nextcloud:
  host: nextcloud.casarp.us
  username: rp
  password: ok

  # Mail config
  mail:
    enabled: false
